language: scala
scala:
  - 2.12.1
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
script:
  - docker pull nginx
  - "sbt clean coverage test it:test"
after_success:
  - "sbt coverageReport"
  - "bash <(curl -s https://codecov.io/bash)"
