language: scala
scala:
  - 2.12.0
jdk:
  - oraclejdk8
#sudo: required
#services:
#  - docker
script: "sbt clean coverage test"
after_success:
  - "sbt coverageReport"
  - "bash <(curl -s https://codecov.io/bash)"
